### ISSUE TITLE
Undefined index: email

### ISSUE THREAD

**Issue by Ahmed-Badawy** [illuminate/socialite#8]
when i used github -- it gave me this: 
ErrorException in GithubProvider.php line 52: Undefined index: email
every thing else is working fine...

**Comment by GrahamCampbell** [comment]
This repo is not supported.

**Comment by johnregalado** [comment]
If you go into the Socialite GithubProvider: vendor/laravel/socialite/src/Two/GithubProvider.php

Scroll down to line 52 and change 'email' => $user['email'] to 'email' => '',

I think github no longer passes user emails and since this repo isn't supported anymore, it hasn't been updated.

From
![screen shot 2015-03-07 at 11 37 56 pm](https://cloud.githubusercontent.com/assets/7155098/6544732/12ac2a5c-c523-11e4-91e3-994b64ab9c68.png)

TO

![screen shot 2015-03-07 at 11 38 08 pm](https://cloud.githubusercontent.com/assets/7155098/6544733/1fdfc274-c523-11e4-8a5f-eaf3f1029586.png)

**Comment by mastacheata** [comment]
You can replace illuminate/socialite by https://github.com/laravel/socialite if you upgrade laravel to version 5.
This code never really got finished for Laravel 4 and they abandoned it shorty after the official release of L4 in favor of a rewrite for L5.

@johnregalado You're looking at the wrong repository here. There is no such file in this repo (laravel/socialite (L5) => vendor/laravel/socialite/src/Two/GithubProvider.php VS illuminate/socialite (L4/not officially included) => vendor/illuminate/socialite/src/Illuminate/Socialite/OAuthTwo/GithubProvider.php)

**Comment by Ahmed-Badawy** [comment]
thanks. 
Please close this issue...

**Comment by GrahamCampbell** [comment]
You need to do that.
